version: "3.8"

services:
  linktree_app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile.local
    working_dir: /usr/src/app
    depends_on:
      - linktree_db
    volumes:
      - .:/usr/src/app
    environment:
      SERVICE_NAME: linktree-app
    networks:
      - app_network

  linktree_nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile.local
    depends_on:
      - linktree_app
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 8010:80
    environment:
      NGINX_FPM_HOST: linktree_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  linktree_db:
    image: mysql:latest
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: linktree
      MYSQL_USER: linktree
      MYSQL_PASSWORD: linktree
      MYSQL_ROOT_PASSWORD: linktree
    networks:
      - app_network

  linktree_redis:
    image: redis:latest
    ports:
      - 6380:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
